name: smieciarka

volumes:
  postgres_data:

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 1g
    cpus: 1.5
    pids_limit: 200
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c shared_buffers=256MB
      -c work_mem=4MB
      -c max_connections=50
